version: "3.8"

include:
  - supabase/docker-compose.studio.yml
  - supabase/docker-compose.yml

services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./website/src/:/app/src/
      - ./website/.env.development:/app/.env.development
