import { getCurrentLang } from "@/lib/server/lang";
import "@/styles/globals.css";
import "@/styles/fonts.css";
// import { Oswald, Poppins } from "next/font/google";
import React from "react";

export const metadata = {
  title: "2M2 Ricambi",
  description: "Generated by create next app",
};

// const poppins = Poppins({
//   subsets: ["latin"],
//   display: "swap",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// const poppins = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// const oswald = Oswald({
//   subsets: ["latin"],
//   display: "swap",
//   weight: ["200", "300", "400", "500", "600", "700"],
//   variable: "--font-oswald",
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={getCurrentLang()}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="text-dark bg-neutral-800">{children}</body>
    </html>
  );
}
